<?php

namespace AppBundle\Repository;

/**
 * PmssRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PmssRepository extends \Doctrine\ORM\EntityRepository
{
}
